env:
  RUBY_VERSION: 2.7.4
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: lofft_web_api_test
  DEVISE_JWT_SECRET_KEY: ${{secrets.DEVISE_JWT_SECRET_KEY}}

name: Rails Specs
on: [push]
jobs:
  rspec-test:
    name: RSpec
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{env.POSTGRES_USER}}
          POSTGRES_PASSWORD: ${{env.POSTGRES_PASSWORD}}
        ports:
          - 5432&/tcp
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      # - uses: actions/checkout@v1
      # - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{env.RUBY_VERSION}}
      - name: Install postgres client
        run: sudo apt-get install libpq-dev
      - name: Install dependencies
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Create database
        run: |
          bin/rails db:setup
      - name: Run tests
        run: bundler exec rspec spec/*
      - name: Upload coverage results
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: coverage-report
          path: coverage
